# Site settings
title: ABC2021
email: abc@sozolab.jp
url: https://abc-research.github.io
description: "International Conference on Activity and Behavior Computing (ABC), which includes Human Activity Recognition with mobile / environmental sensors in ubiquitous / pervasive domains and with cameras in vision domains, and Human Behavior Analysis for long-term health care, rehabilitation, emotion recognition, human interaction, and so on."
keywords: "activity recognition, behavior analysis, international conference, activity and behavior computing"
conf_title1: "The 3rd International Conference on"
conf_title2: "Activity and Behavior Computing"
meta_author: Sozo Inoue
location: Knowledge Exchange Center (KX), Bangkok, Thailand (<b style="color:yellow">Changed to Online</b>)
date: Oct. 20th - 23rd, 2021
conjunction:
  name: ICIEV&IVPR2021
  url: http://cennser.org/ICIEV/
  
navitem:
  - name: About
    url: "#about"
#  - name: Registration
#    url: "https://sites.google.com/view/iciev-abc-2020-payment"
#  - name: Program
#    url: "#program"
  - name: CFP
    url: "#cfp" 
  - name: Challenge
    url: "https://abc-research.github.io/bento2021/"
  - name: Venue
    url: "#venue"
  - name: Committee
    url: "#committee"
  - name: Series
    url: "#series"
    
includes:
  - file: header.html
#  - file: sponsors.html
  - file: about.html
#  - file: program.html
  - file: cfp.html
  - file: venue.html
  - file: committee.html
  - file: series.html
  


# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ee6128
  primary-rgb: "238,97,40"
  secondary: 444648 
  secondary-dark: 444648 

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

about:
  - text: "<b>Human Activity Recognition</b> has been researched in thousands of papers so far, with mobile / environmental sensors in ubiquitous / pervasive domains, and with cameras in vision domains. As well, <b>Human Behavior Analysis</b> is also explored for long-term health care, rehabilitation, emotion recognition, human interaction, and so on. However, many research challenges remain for realistic settings, such as complex and ambiguous activities / behavior, optimal sensor combinations, (deep) machine learning, data collection, platform systems, and killer applications."
  - text: "In this conference, we comprehend such research domains as <b>ABC</b>: <i>Activity and Behavior Computing</i>, and provide an open and a confluent place for discussing various aspects and the future of the ABC."

# accepted papers (temporary)
accepted:
  - category: Regular Papers
    paper: 
    - title:	Improvement of Human Action Recognition Using 3D Pose Estimation
      authors:	Kohei Adachi (Kyushu Institute of Technology)*; Paula Lago (Kyushu Institute of Technology ); Tsuyoshi Okita (Kyushu Institute of Technology); Sozo Inoue (Kyushu Institute of Technology)
    - title:	Reducing Energy Consumption by Behavioural Change – It is possible!
      authors:	Dietrich Albert (University of Graz & Graz University of Technology)*; Michael Bedek (University of Graz & Graz University of Technology); Wolfgang Horn (Horn Consult, Leibnitz)
  - category: "Non-archival Papers"
    paper:
    - title:	Exploring the use of accelerometer for assisting weight lifting exercise
      authors:	Nour Alhuda Al bougha (Kyushu Institute of Technology)*; Sozo Inoue (Kyushu Institute of Technology); brahim benaissa (kyushu institute of technology)
    - title:	Towards New Performance Metrics for Multi-level Data for Activity Recognition
      authors:	Sayeda Shamma Alia (Kyushu Institute of Technology)*; Paula Lago (Kyutech); Sozo Inoue (Kyushu Institute of Technology)

# Committee members
committee:
  - role: General Chairs
    member:
      - name: Sozo Inoue
        affil: Kyushu Institute of Technology / AUTOCARE LLC, Japan
      - name: Atiqur Rahman Ahad
        affil: University of Dhaka, Bangladesh / Osaka University, Japan
  - role: Program Chairs
    member:
      - name: Daniel Roggen
        affil: University of Sussex, UK
      - name: Kaori Fujinami
        affil: Tokyo University of Agriculture and Technology, Japan
  - role: Publicity Chairs
    member:
      - name: Paula Lago
        affil: Kyushu Institute of Technology, Japan
      - name: Anja Exler
        affil: Adastra, Germany
      - name: Hiroki Watanabe
        affil: Hokkaido University, Japan
  - role: Publication Chair
    member:
      - name: Tahera Hossain
        affil: Aoyama Gakuin University, Japan        
  - role: Local Organization Chair
    member:
      - name: Phond Phunchongharn
        affil: KMUTT, Thailand
  - role: Advisory Board
    member:
      - name: Paul Lukowicz
        affil: DFKI, Germany
      - name: Kristof Van Laerhoven
        affil: University of Siegen, Germany
      - name: Daniel Roggen
        affil: University of Sussex, UK
      - name: Michael Beigl
        affil: Karlsruhe Institute of Technology, Germany
      - name: Jeffry Cohn
        affil: University of Pittsburgh, USA
      - name: Anind Dey
        affil: University of Washinton, USA
      - name: Nobuo Kawaguchi
        affil: Nagoya University, Japan
  - role: Secretaries
    member:
#      - name: Moe Matsuki
#        affil: Kyushu Institute of Technology, Japan
      - name: Nattaya Mairittha
        affil: Kyushu Institute of Technology, Japan
      - name: Tittaya Mairittha
        affil: Kyushu Institute of Technology, Japan
  - role: Program Committee
    member:
      - name: Ren Ohmura
        affil: Toyohashi University of Technology, Japan
      - name: Kazuya Murao
        affil: Ritsumeikan University, Japan
      - name: Kristof Van Laerhoven
        affil: University of Siegen, Germany
      - name: Susanna Pirttikangas
        affil: University of Oulu, Finland
      - name: Philipp M. Scholl
        affil: University of Freiburg, Germany
      - name: Hristijan Gjoreski
        affil: Ss. Cyril and Methodius University, Macedonia
      - name: Katsuhiko Kaji
        affil: Aichi Institute of Technology, Japan
      - name: Tsuyoshi Okita
        affil: Kyushu Institute of Technology / Riken, Japan
      - name: Paula Lago
        affil: Kyushu Institute of Technology, Japan
      - name: Stephan Sigg
        affil: Aalto University, Finland
      - name: Hiroki Watanabe
        affil: Hokkaido University, Japan
      - name: Pascal Hirmer
        affil: University of Stuttgart, Germany
      - name: Shigeyuki Miyagi
        affil: The University of Shiga Prefecture, Japan
      - name: Yu Enokibori
        affil: Nagoya University, Japan
      - name: Anja Exler
        affil: Adastra, Germany
      - name: Kristina Yordanova
        affil: University of Rostock, Germany
      - name: Trung Thanh NGO
        affil: Osaka University, Japan
#      - name: Ricky J Sethi
#        affil: Fitchburg State University, USA
#      - name: Ikuhisa Mitsugami
#        affil: Hiroshima City University, Japan
#      - name: Mohiuddin Ahmad	
#        affil: Khulna University of Engineering & Technology, Bangladesh
      - name: Upal Mahbub
        affil: University of Meryland, College Park, USA
      - name: Atsushi Shimada
        affil: Kyushu University, Japan
      - name: Guillaume Lopez
        affil: Aoyama Gakuin University, Japan        
      - name: Atsushi Nakazawa
        affil: Kyoto University, Japan
      - name: Liming Chen
        affil: Ulster University, UK
      - name: Christopher Nugent
        affil: Ulster University, UK
      - name: François Charpillet 
        affil: INRIA, France
      - name: Maria Del Pilar Villamil Giraldo
        affil: University of Los Andes, Colombia
#      - name: Shoji Kobashi
#        affil: University of Hyogo, Japan
      - name: Takuro Yonezawa
        affil: Nagoya University, Japan
      - name: Anna Yokokubo
        affil: Aoyama Gakuin University, Japan

    
cfp:
  text:
    - text: "We welcome 4 categories of papers: regular  papers, position papers, survey papers, and challenge papers. The submitted papers are <u>peer reviewed</u> by expert researchers, and accepted based on the research quality."
    - text: "Accepted papers will be included in the <a href='https://www.springer.com/series/8767' style='color:white'>Smart Innovation, Systems and Technologies series</a> of <u>Springer books</u> (Indexed in ISI Proceedings, EI-Compendex, SCOPUS, Google Scholar and Springerlink)."
#    - text: "Selected papers will be invited to submit to the <u>Pattern Recognition Letters</u> journal (5-Year Impact Factor: 2.350) and to <u>International Journal on Computer Vision and Signal Processing</u>."
#    - text: To accept various research stages, an accepted paper can be either published in IEEE proceedings + USB, Open web + USB, or USB only upon authors' preference."
  scope:
    - item: Mobile sensor-based ABC
    - item: Environmental sensor-based ABC
    - item: Vision-based ABC
    - item: Multimodal ABC
    - item: Physical / semantic analysis of ABC
    - item: Gait analysis
    - item: Sleep analysis
    - item: Emotion recognition / analysis
    - item: ABC with deep learning
    - item: ABC data mining
    - item: Data collection
    - item: ABC systems
    - item: Interactive ABC
    - item: Healthcare applications
    - item: Sports applications
    - item: Business applications
    - item: Tools for industry
    - item: ABC in the wild
  category:
    - item: "<b>Regular papers</b>: full technical contents which describe the accuracy and performance of ABC Systems, real deployment cases or application of new paradigms such as deep learning to ABC. "
    - item: "<b>Survey papers</b>: new perspective or new challenges in ABC based on literature survey. We do not welcome just compilations of existing research, but do if it provides new research horizons."
    - item: "<b>Challenge papers</b>: we will provide a dataset and accept results for activity recognition and papers describing the methods and the results. Please see the <a href='https://abc-research.github.io/bento2021'><b style='color:yellow';>Challenge Site)</b></a> for details."
    - item: "<b>Position papers</b>: describe the challenges and future directions of ABC based on  problems that arise when systems are deployed in real settings."
  format: 
     - item: "<b>Regular papers</b>: 8-20 pages in single column"
     - item: "<b>Survey papers</b>: 10-20 pages in single column"
     - item: "<b>Challenge papers</b>: 4-10 pages in single column"
     - item: "<b>Position papers</b>:  4-10 pages in single column"
     - item: "Please use Springer Contributed Book format (button below for the LaTeX template)."
     - item: "Submit from Microsoft CMT service (button below) and select the ABC."
     - item: "Note that the <b>author information should be removed</b> from the paper, for double blind reviews."
  dates:
    - name: "[Regular/Survey/Position] Paper submission"
      date: <b><span style="color:yellow"> Aug. 20th, 2021 (Extended!)</span></b> (Anywhere on Earth)!
# <strike style="color:gray">Jul. 2nd</strike>      
    - name: "Review result"
      date: Sep. 10th, 2021
#<strike style="color:gray">Aug. 23rd</strike> 
    - name: "Resubmission for conditionally accepted paper"
      date: Sep. 24th, 2021
      #<strike style="color:gray">Sep. 1st</strike> 
    - name: <span style="color:#CEF9DC">[Challenge] Application</span>
      date: <span style="color:#CEF9DC">Aug. 17th, 2021 <b>(Extended!)</b> (Anywhere on Earth)!</span>
#    <strike style="color:gray">Jul. 1st</strike> 
    - name: <span style="color:#CEF9DC">[Challenge] Result submission</span>
      date: <span style="color:#CEF9DC">Aug. 17th, 2021 (Anywhere on Earth)!</span>
#       <strike style="color:gray">Aug. 1st</strike>
# Aug. 9th: review deadline
    - name: <span style="color:#CEF9DC">(Challenge) Paper submission</span>
      date: <span style="color:#CEF9DC">Aug. 20th, 2021  (Anywhere on Earth)!</span>
#      <strike style="color:gray">Aug. 1st</strike>
    - name: <span style="color:#CEF9DC">(Challenge) Review result</span>
      date: <span style="color:#CEF9DC">Sep. 2nd, 2021</span>
# <strike style="color:gray">Aug. 23rd</strike>      
    - name: '[Regular/Survey/Position/Challenge] Camera ready and Registration'
      date: Oct. 1st, 2021
      #<strike style="color:gray">Sep. 7th</strike> 
# Sep. 15th: submit to the publisher
    - name: "Conference"
      date: Oct. 20th - 23rd, 2021
  submit_url: https://cmt3.research.microsoft.com/ABC2021/Submission/Index
  template_url: https://ja.overleaf.com/latex/templates/template-for-authors-to-a-springer-contributed-volume/bbfkkmdbdtcy

venue:
  - text: ABC2021 will be held <strike>at Knowledge Exchange Center (KX), Bangkok, Thailand</strike> (<b style="color:orange">Changed to Online</b>). KX is the exchange center for academia and start-ups.
#  - text: For more information, please see <a href="https://www.kxinnovation.com/en">here</a>.
#  - text: We are considering to do it <b>either of hybrid or online style</b>. Anyway we provide online participation at least.
#  - text: <div class="movie-wrap"><iframe width="700" height="485" src="https://www.youtube.com/embed/8ZYPX7xI7ZE?list=PLP-mfYAs9cGw5kQfBfNCKbralx3a5xSoi" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ABC_Conference
  - title: facebook
    url: https://fb.me/ActivityBehaviorComputingConference
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
#  - title: github
#    url: http://github.com/abc-research

series:
  - text: "<b>ABC2020</b>: International Conference on Activity and Behavior Computing @Kitakyushu, Japan"
    url: https://abc-research.github.io/2020
  - text: "<b>ABC2019</b>: International Conference on Activity and Behavior Computing @Spokane, US"
    url: https://abc-research.github.io/2019
  - text: "<b>Bento2021</b>: Bento Packaging Activity Recognition Challenge in ABC2021"
    url: https://abc-research.github.io/bento2021a
  - text: "<b>Cook2020</b>: Cooking Activity Recognition Challenge in ABC2020 @Kitakyushu, Japan"
    url: https://abc-research.github.io/cook2020
  - text: "<b>Nurse2021</b>: Third Nurse Care Activity Recognition Challenge - Can we Do from Bigdata? - in HASCA2021"
    url: https://abc-research.github.io/nurse2021
  - text: "<b>Nurse2020</b>: Second Nurse Care Activity Recognition Challenge - From Lab to Field - in HASCA2020"
    url: https://abc-research.github.io/nurse2020
  - text: "<b>Nurse2019</b>: Nurse Care Activity Recognition Challenge 2019 in HASCA2019 @London"
    url: https://hasc-nurse-challenge.github.io
  - text: "<b>HASCA2019</b>: International Workshop on Human Activity Sensing Corpus and Applications @London"
    url: http://hasca2019.hasc.jp


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
